<template>
  <v-card-title>臨時タスクテスト001</v-card-title>
  <v-card-text>臨時タスクテスト001臨時タスクテスト001臨時タスクテスト001臨時タスクテスト001</v-card-text>
  <v-card-item>
    <v-card-subtitle>適用期間</v-card-subtitle>
    <v-card-text>2022-05-10 - 2022-07-31</v-card-text>
  </v-card-item>
  <v-card-item>
    <v-card-subtitle>実施回数</v-card-subtitle>
    <v-card-text>期限指定</v-card-text>
  </v-card-item>
  <v-card-item>
    <v-card-subtitle>オプション</v-card-subtitle>
    <v-card-text>***</v-card-text>
  </v-card-item>
  <v-card-item>
    <v-card-subtitle>タグ</v-card-subtitle>
    <v-card-text>***</v-card-text>
  </v-card-item>
</template>